### ISSUE TITLE
java.util.ConcurrentModificationException when requesting access token with Keycloak Events plugin enabled. KC25.0.1

### ISSUE THREAD

**Issue by Jack-Hazelden-Blackdot** [p2-inc/keycloak-events#76] opened 2024-10-08 10:35 UTC
Upon enabling the Keycloak Events plugin we see errors consistently raised in our tests when setting up the realms for our testing environment causing them to fail with a `java.util.ConcurrentModificationException` in the logs.

All instances of the error appear to be when `Keycloak.Net.KeycloakClient` in our backend requests an access token from `POST http://keycloak:8080/realms/tests/protocol/openid-connect/token` as part of the authentication flow causing Keycloak to return a 500. Note that prior to enabling the Keycloak Events plugin this did not occur, and disabling it allows the tests to pass with no issues.

For our test runs we stand up Keycloak using docker compose in Github Actions and configure it to use the `jboss-logging` and `ext-event-http` event listeners via a bootstrapper - we then stand up our backend using docker run on the same network where it hits the Keycloak endpoints. Section of the docker compose configuring Keycloak:

```
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: <admin_name>
      KEYCLOAK_ADMIN_PASSWORD: <admin_password>
      JAVA_OPTS_APPEND: "-server -Xms128m -Xmx256m"
    ports:
      - "8081:8080"
    volumes:
      - ../../src/keycloak/keycloak-events-plugin/keycloak-events-0.32-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-events-0.32-SNAPSHOT.jar:ro
```
 
Versions used and logs are below - any assistance is greatly appreciated. Let me know if any additional information is required. Quite possibly related to https://github.com/p2-inc/keycloak-events/issues/73

Keycloak version: 25.0.1
Keycloak Events plugin version: 0.32
Keycloak.Net.Core version: 1.0.26
Keycloak.AuthServices.Authentication version: 2.5.1

From our backend logs calling Keycloak:

```
>    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
>    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
> {"Timestamp":"2024-10-07 12:01:26Z","EventId":0,"LogLevel":"Error","Category":"Bds.Common.Mediator.RequestLoggingBehaviour","Message":"Error handling UpdateOrganisationLicenceCommand","Exception":"Flurl.Http.FlurlHttpException: Call failed with status code 500 (Internal Server Error): POST http://keycloak:8080/realms/tests/protocol/openid-connect/token
>    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
>    at Flurl.Http.ResponseExtensions.ReceiveJson(Task\u00601 response)
>    at [Keycloak.Net](http://keycloak.net/).Common.Extensions.FlurlRequestExtensions.GetAccessTokenAsync(String url, String realm, String clientSecret, KeycloakOptions options)
>    at [Keycloak.Net](http://keycloak.net/).Common.Extensions.FlurlRequestExtensions.GetAccessToken(String url, String realm, String clientSecret, KeycloakOptions options)
>    at [Keycloak.Net](http://keycloak.net/).Common.Extensions.FlurlRequestExtensions.WithAuthentication(IFlurlRequest request, Func\u00601 getToken, String url, String realm, String userName, String password, String clientSecret, KeycloakOptions options)
>    at [Keycloak.Net](http://keycloak.net/).KeycloakClient.GetBaseUrl(String authenticationRealm)
>    at [Keycloak.Net](http://keycloak.net/).KeycloakClient.GetUsersWithRoleNameAsync(String realm, String roleName, Nullable\u00601 first, Nullable\u00601 max, CancellationToken cancellationToken)
```

From the Keycloak logs at the same point in time:

```
> keycloak-1  | 2024-10-07 12:01:26,543 INFO  [io.phasetwo.keycloak.events.HttpSenderEventListenerProviderFactory] (executor-thread-2) Configuring io.phasetwo.keycloak.events.HttpSenderEventListenerProvider with [targetUri=http://audit:8080/keycloak]
> keycloak-1  | 2024-10-07 12:01:26,559 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.util.ConcurrentModificationException
> keycloak-1  | 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1076)
> keycloak-1  | 	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:385)
> keycloak-1  | 	at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_XoSEUTXOsE3bpqXlGMAykCiECUM_ClientProxy.close(Unknown Source)
> keycloak-1  | 	at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:60)
> keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.closeSession(CloseSessionFilter.java:67)
> keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.filter(CloseSessionFilter.java:63)
> keycloak-1  | 	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
> keycloak-1  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
> keycloak-1  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
> keycloak-1  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
> keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> keycloak-1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
> keycloak-1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
> keycloak-1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> keycloak-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
> keycloak-1  |
```

**Comment by xgp** [comment] 2024-10-08 10:58
@Jack-Hazelden-Blackdot Can you also provide information on how you are configuring the `ext-event-http` listener (i.e. what realm attributes you are setting, and how)? We'll try to reproduce.

The code the exception points to seems to indicate that the internal `Map` of providers kept by the `DefaultKeycloakSession` implementation is somehow getting changed while it is looping through the providers to call `close`. That's strange because we don't make any changes (nor do I think we can) to that `Map`. 

https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java#L385C1-L386C1

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-08 11:49
@xgp For the realm attribute configuration of the `ext-event-http` listener we set the `_providerConfig.ext-event-http` with the `targetUri` to our auditing service endpoint (`http://audit:8080/keycloak`) as part of the bootstrapping by calling the Keycloak API - this service is stood up using docker run in the same network. Example of the code:

```
private async Task AddProviderConfigurationAsync(string auditEventServiceName)
    {
        await _realmsAdminApi.PutAsync(_realm, new RealmRepresentation
        {
            Attributes = new Dictionary<string, string>()
            {
                {"_providerConfig.ext-event-http", $"{{\"targetUri\":\"{auditEventServiceName}\"}}"}
            }
        });
    }
```

The logs from the audit service indicate that Keycloak is able to connect and push events through:

> [11:59:58 INF] Now listening on: http://[::]:8080
> [11:59:58 INF] Application started. Press Ctrl+C to shut down.
> [11:59:58 INF] Hosting environment: CucumberCi
> [11:59:58 INF] Content root path: /app
> [12:01:26 INF] Request starting HTTP/1.1 POST http://audit:8080/keycloak - application/json 514
> [12:01:26 INF] Request starting HTTP/1.1 POST http://audit:8080/keycloak - application/json 514
> [12:01:26 WRN] Failed to determine the https port for redirect.
> [12:01:26 INF] Executing endpoint 'HTTP: POST /keycloak'
> [12:01:26 INF] Executing endpoint 'HTTP: POST /keycloak'
> [12:01:26 INF] Setting HTTP status code 200.
> [12:01:26 INF] Setting HTTP status code 200.
> [12:01:26 INF] Executed endpoint 'HTTP: POST /keycloak'
> [12:01:26 INF] Executed endpoint 'HTTP: POST /keycloak'
> [12:01:26 INF] HTTP POST /keycloak responded 200 in 36.8933 ms
> [12:01:26 INF] HTTP POST /keycloak responded 200 in 29.3713 ms
> [12:01:26 INF] Request finished HTTP/1.1 POST http://audit:8080/keycloak - 200 0 null 122.9871ms
> [12:01:26 INF] Request finished HTTP/1.1 POST http://audit:8080/keycloak - 200 0 null 123.1193ms

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-14 15:03
@xgp I was looking through the link you attached to the Keycloak repo and noticed there was a comment in the file around the ConcurrentModificationException that mentions the version of the JDK having an impact - I was wondering if it was possible that whether our method of building the plugin jar could be responsible.

>  // KEYCLOAK-11890 - Avoid using HashMap.computeIfAbsent() to implement logic in outer if() block below,
>  // since per JDK-8071667 the remapping function should not modify the map during computation. While
>  // allowed on JDK 1.8, attempt of such a modification throws ConcurrentModificationException with JDK 9+

This is what we use to build the plugin:

```
FROM registry.access.redhat.com/ubi9/ubi:latest AS build
WORKDIR /src
RUN dnf install -y git java-21-openjdk-devel maven-openjdk17
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
RUN git clone https://github.com/p2-inc/keycloak-events.git
WORKDIR /src/keycloak-events
RUN mvn clean install -DskipTests=true

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
# BREAKCACHE Force update layer to run.
ARG BREAKCACHE
RUN echo "${BREAKCACHE}" && rm -f /etc/rhsm-host && \
    microdnf -y --releasever 9 --setopt install_weak_deps=0 --nodocs update && \
    microdnf -y clean all && rm -rf /var/cache/yum && rm -rf /var/cache/dnf rm -r /var/lib/rpm/rpmdb.sqlite
COPY ["licenses", "/licenses"]
WORKDIR /src
COPY --chown=1001:0 --from=build /src/keycloak-events/target/keycloak-events-*-SNAPSHOT.jar .
ARG version
USER 1001
```

Not sure if that is useful. Have you been able to replicate at all?

**Comment by xgp** [comment] 2024-10-14 16:50
@Jack-Hazelden-Blackdot I have not been able to reproduce.

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-16 09:43
@xgp Would you be able to share your test setup at all? If there is a misconfiguration on our end it may help with diagnosing it.

Many thanks!

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-24 09:35
@xgp I managed to take some more time to look at this an believe I've identified a possible cause for the errors I've been seeing.

In the Keycloak 25 upgrade the `SimpleHttp.doPost` method that takes an `HttpClient` was [modified](https://github.com/keycloak/keycloak/commit/6de5325d1c49053a8f5bfd84ed4a5a7646ea3a65#diff-74b329bccaf6b7c7fb0f833825a03c1801e7234f152634f33c725bb145f77435L117) so that it is a protected method, as a consequence only the `doPost` method that takes a `KeycloakSession` can be called publicly.

As a result the eventing plugin had to change for Keycloak 25+ to pass `doPost` the `KeycloakSession` - [here](https://github.com/p2-inc/keycloak-events/commit/253c014e0e6f45479b64dafbd1cfae2fd518bac4#diff-3aca41dc80b8454711f863f02635a5acc47741da3299d03cdcac152d632ca01aL75)

What I did locally to test was add a copy of the current Keycloak version of `SimpleHttp` to the src of `keycloak-events` with a unique name and made the original `doPost` that takes an `HttpClient` public again, then effectively rolled back [this](https://github.com/p2-inc/keycloak-events/commit/253c014e0e6f45479b64dafbd1cfae2fd518bac4#diff-3aca41dc80b8454711f863f02635a5acc47741da3299d03cdcac152d632ca01aL75) change and replaced `SimpleHttp` with this test version so the connection behaviour is reverted to how it was with Keycloak 24.

After doing this I no longer get the `java.util.ConcurrentModificationException`, which makes me suspect there is a concurrency issue with how the Keycloak session is used when sending multiple events in a short period of time.

Obviously, modifying the source code like this isn't a solution - is this something you can look into? On another note is it something that needs to be raised with the main Keycloak repo at all?

Thanks again

**Comment by xgp** [comment] 2024-10-25 08:44
@Jack-Hazelden-Blackdot Can you please test against the https://github.com/p2-inc/keycloak-events/tree/xgp/simplehttp-legacy branch? We've copied the "old" `SimpleHttp` class in a couple of other extensions, so I don't see the problem in doing it here.

**Comment by xgp** [comment] 2024-10-25 08:46
> On another note is it something that needs to be raised with the main Keycloak repo at all?

I think they would probably say it's for their internal use and not to use it. I think our strategy should be to move off of internal Keycloak utilities like this, as they seem to always be changing and breaking things.

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-25 10:03
@xgp Thanks - I'll give it a look today and get back to you

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-25 16:10
@xgp I had to make a minor change, but after that everything worked. What I did was pass an `HttpClient` directly to the `LegacySimpleHttp.doPost` method inside `HttpSenderEventListenerProvider` instead of the session.

![image](https://github.com/user-attachments/assets/8dc6681e-db36-45e9-98cc-4805a2bcdaca)

```
protected void send(
      SenderTask task, String targetUri, Optional<String> sharedSecret, Optional<String> algorithm)
      throws SenderException, IOException {
    log.debugf("attempting send to %s", targetUri);
    try (CloseableHttpClient http = HttpClients.createDefault()) {
      LegacySimpleHttp request = LegacySimpleHttp.doPost(targetUri, http).json(task.getEvent());
```

I did try to make a PR onto your branch, but obviously I didn't have permissions.

**Comment by xgp** [comment] 2024-10-25 16:18
fixed in d28390e

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-25 16:21
Great, thanks! I can give it another go with that to confirm Monday morning if you like?

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-28 09:28
@xgp Tested using the new build and all seems to be working for me

**Comment by xgp** [comment] 2024-10-28 09:29
Fixed by https://github.com/p2-inc/keycloak-events/pull/80

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-28 09:30
Great, thanks a lot!

**Closed by xgp** 2024-10-28 09:29 UTC
Labels: bug

**Comment by Jack-Hazelden-Blackdot** [comment] 2024-10-29 10:56
@xgp Just to confirm - now this is merged it is considered released?

**Comment by xgp** [comment] 2024-10-29 11:44
Our process is that a merge to main creates a tag and releases to Maven Central. In this case:

https://github.com/p2-inc/keycloak-events/tree/v0.34

https://search.maven.org/artifact/io.phasetwo.keycloak/keycloak-events/0.34/jar
