### ISSUE TITLE
Version 0.31 broke forwarding of admin events

### ISSUE THREAD

**Issue by FileJunkie** [p2-inc/keycloak-events#71] opened 2024-08-28 12:40 UTC
This change in handling Realms for admin events: [v0.30...v0.31](https://github.com/p2-inc/keycloak-events/compare/v0.30...v0.31#diff-5b64cd30a18688d3d47300cabb1ebfa8d072da713dc1c8768b13072dea44199f) assumes that the realm of an event and the realm in the `AuthDetails` field are the same while they are not: in case of `admin.GROUP_MEMBERSHIP-CREATE`, `admin.GROUP_MEMBERSHIP-DELETE`, and `admin.USER-DELETE` events `realmId` field of the event itself is the realm of the user in question, but `AuthDetails.realmId` is the realm of whoever touched that user, and these two values can be different when, for example, a global admin is editing a user in non-`master` realm.

This issue is not theoretical, we ran into it in production.

**Comment by xgp** [comment] 2024-08-28 15:30
@rtufisi looks like the fix to #66 introduced another issue. Can you review and see if we can reconcile both issues?

**Comment by rtufisi** [comment] 2024-08-29 05:34
Sure. I will look into it

**Comment by rtufisi** [comment] 2024-08-30 06:35
@xgp . From what I understand:
ExtendedAdminEvent.extAuthDetails must contain the

**Comment by rtufisi** [comment] 2024-08-30 14:37
From what I understand:
Keycloak event:

```
"AdminEvent" : {
authDetails: {
    "realmId" -realm of the user which is loggedIn;
    "userId" - logged inUser;
}
......
realmId: "realm on which the action is performed"
}

```

Extended event(the one send in the webhook)
```
`ExtendedAdminEvent.extAuthDetails `must contain the
    realmId -realmId  on which the action is performed
    userId - user which performs the action (user which you are logged in and performs the action - it can be from master realm or another realm )
```

**Comment by rtufisi** [comment] 2024-08-30 14:39
PR https://github.com/p2-inc/keycloak-events/pull/72. Pleaase check @xgp

**Comment by xgp** [comment] 2024-08-30 17:12
@FileJunkie Please run against the `rtufisi:77-fix-event-webook` branch in #72 to see if that fixes your issue.

**Comment by FileJunkie** [comment] 2024-09-03 12:14
@xgp  @rtufisi yes, it fixed our issue.

**Comment by xgp** [comment] 2024-09-03 18:41
fixed in #72

**Comment by FileJunkie** [comment] 2024-09-04 10:52
Hmmm, it's really weird, but it seems that 0.32 is broken again, in our system at least, with the same realm problem, though the branch worked. I can't really pinpoint the issue this time though.

**Comment by xgp** [comment] 2024-09-04 11:02
@FileJunkie Thanks for the report. Please write a junit test for your case that reproduces the issue, and then PR the fix.

**Comment by FileJunkie** [comment] 2024-10-15 11:28
@xgp 

Hi again, I finally found some time to investigate the issue and I think I found it.

If you take a look at @rtufisi's [branch](https://github.com/rtufisi/keycloak-events/blob/77-fix-event-webook/src/main/java/io/phasetwo/keycloak/events/WebhookSenderEventListenerProvider.java), where event delivery works just fine, the line 160 contains this:

```RealmModel realm = session.realms().getRealm(adminEvent.getRealmId());```

However, in [release 0.32](https://github.com/p2-inc/keycloak-events/blob/v0.32/src/main/java/io/phasetwo/keycloak/events/WebhookSenderEventListenerProvider.java), which doesn't work, the same line says:

```RealmModel realm = session.realms().getRealm(adminEvent.getAuthDetails().getRealmId());```

I guess this is the issue. Could you guys please take a look? Should I open another issue for that?

**Comment by xgp** [comment] 2024-10-15 11:40
Please submit a PR that works for you, along with a test case.

**Comment by xgp** [comment] 2024-10-15 13:47
An integration test that reproduces the problem before your fix, and demonstrates that the issue is solved after the fix. Thank you!

**Comment by FileJunkie** [comment] 2024-10-21 12:04
Hi there @xgp , PR is here: https://github.com/p2-inc/keycloak-events/pull/79. Any chance for it to be reviewed or you have some extra requirements?

**Comment by xgp** [comment] 2024-10-21 17:28
@rtufisi could you please look at this PR?

**Comment by xgp** [comment] 2024-10-28 16:25
3 cases i can think we need to test

- event from `master` realm when logged in to `master` realm
- event from `test` realm when logged in to `master` realm
- event from `test` realm when logged in to `test` realm

Can we write tests for those?

**Comment by FileJunkie** [comment] 2024-11-15 11:33
Hi there, did you guys have any chance to write these tests?

**Comment by xgp** [comment] 2024-11-15 11:35
Sorry, I think you misunderstood. We're happy to review, but you need to write the tests if this is going to get merged.

**Comment by FileJunkie** [comment] 2024-11-15 11:37
Ah, you said can "we" write the tests for that, hence I though it's on you, OK, thanks for clarification.

**Comment by FileJunkie** [comment] 2024-11-17 15:21
I added the tests for all three cases you wished to cover - and also improved my fix.

**Comment by FileJunkie** [comment] 2024-11-26 13:56
More tests and checks added, as requested.

**Closed** 2024-11-26 18:00 UTC
Labels: bug
